library(lubridate)
library(data.table)
setwd("Desktop/Developer/DataScience/exploratory-data-analysis/ExData_Plotting1/data/")
data <- fread("household_power_consumption.txt",header = TRUE,sep = ";")
data$Date <- dmy(data$Date)
data <- subset(data,data$Date == "2007-02-01" | data$Date == "2007-02-02")
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Date <- ymd_hms(paste(data$Date,data$Time))
# from here
png("plot4.png",height = 480,width = 480)
par(bg = "gray20",mfrow = c(2,2))
plot(data$Date,data$Global_active_power,type ="l",xlab = "",ylab = "Global Active Power")
plot(data$Date,data$Voltage,type ="l",xlab = "datetime",ylab = "Voltage")
plot(data$Date,data$Sub_metering_1,type = "l",ylab = "Energy Sub Metering",xlab = "")
lines(data$Date,data$Sub_metering_2,type = "l",col = "red")
lines(data$Date,data$Sub_metering_3,type = "l",col = "blue")
legend("topright",lty=1,col = c("black","blue","red"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$Date,data$Global_reactive_power,type ="l",xlab = "datetime",ylab = "Global_reactive_power")
dev.off()